name: Containerization

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag to containerize'
        required: true

concurrency:
  group: Containerization-${{ github.event.inputs.tag }}
  cancel-in-progress: false
  
jobs:
  Container:
    strategy:
      matrix:
        config:
            - { name: 'macOS Intel', runner: 'macos-15-intel',     base_image: 'ubuntu:22.04' }
            - { name: 'macOS Apple Silicon', runner: 'macos-latest', base_image: 'ubuntu:22.04' }
    runs-on: ${{ matrix.config.runner }}
    steps:
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout base repo
        run: |
          git clone --branch ${{ github.event.inputs.tag }} --depth 1 https://github.com/MFlowCode/MFC.git mfc
    
      - name: Checkout PR repo
        uses: actions/checkout@v3
        with:
          path: pr

      - name: Prepare Docker context
        run: |
          sudo mkdir -p /mnt/share
          sudo chmod 777 /mnt/share
          rm -rf /mnt/share/*
          cp -r mfc/* /mnt/share/
          cp -r mfc/.git /mnt/share/.git
          cp pr/.github/Dockerfile /mnt/share/
          cp pr/.github/.dockerignore /mnt/share/

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          builder: default
          context: /mnt/share
          file: /mnt/share/Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.config.base_image }}
            TARGET=${{ matrix.config.name }}
            CC_COMPILER=${{ contains(matrix.config.name, 'gpu') && 'nvc' || 'gcc' }}
            CXX_COMPILER=${{ contains(matrix.config.name, 'gpu') && 'nvc++' || 'g++' }}
            FC_COMPILER=${{ contains(matrix.config.name, 'gpu') && 'nvfortran' || 'gfortran' }}
            COMPILER_PATH=${{ contains(matrix.config.name, 'gpu') && '/opt/nvidia/hpc_sdk/Linux_x86_64/compilers/bin' || '/usr/bin' }}
            COMPILER_LD_LIBRARY_PATH=${{ contains(matrix.config.name, 'gpu') && '/opt/nvidia/hpc_sdk/Linux_x86_64/compilers/lib' || '/usr/lib' }}
          tags: sbryngelson/mfc:${{ github.event.inputs.tag }}-${{ matrix.config.name }}-${{ matrix.config.runner}}
          push: true
