name: CI Workflow Groups

on:
  workflow_run:
    workflows:
      - lint-toolchain.yml
      - lint-source.yml
      - spelling.yml
      - formatting.yml
      - pmd.yml
      - line-count.yml
      - coverage.yml
      - cleanliness.yml
      - docs.yml
      - deploy-tap.yml
      - homebrew.yml
    types:
      - completed

jobs:
  job_in_b:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Quality Check workflows finished successfully.
             Running testing & benchmarking workflows."
  
  test-suite:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/test.yml

  benchmarks:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/bench.yml