name: Quality Checks

on:
  workflow_run:
    workflows:
      - "Lint Toolchain"
      - "Lint Source"
      - "Spell Check"
      - "Pretty"
      - "Source DRYness"
      - "Lines of Code"
      - "Coverage Check"
      - "Cleanliness"
      - "Documentation"
      - "Deploy Homebrew Tap"
      - "Homebrew Formula Test"
    types:
      - completed

jobs:
  gate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Quality Check workflows finished successfully.
             Running testing & benchmarking workflows."
  
  test-suite:
    needs: gate
    uses: ./.github/workflows/test.yml

  benchmarks:
    needs: gate
    uses: ./.github/workflows/bench.yml