name: Phoenix CPU - Profiling

on: [push, pull_request, workflow_dispatch]

jobs:    
  pmd:
      name: phoenix-cpu - PMD Fortran
      runs-on: "ubuntu-latest"
      env:
          pr_everything: 0
      steps:
          - name: Clone - PR
            uses: actions/checkout@v4

          - name: Run CPD for Fortran
            continue-on-error: true
            run: |
              profilu