name: Reporting Benchmark Results

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag to bench'
        required: true

permissions:
  contents: write
  deployments: write
  pages: write
  id-token: write

jobs:
  self:
    name: "Continuous Benchmarking"
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Clone - PR
        uses: actions/checkout@v4
        with:
          path: pr

      - name: Setup
        run: | 
          sudo apt-get update -y
          sudo apt-get install -y cmake gcc g++ python3 python3-dev hdf5-tools \
                    libfftw3-dev libhdf5-dev openmpi-bin libopenmpi-dev

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Continuous Benchmarking
          tool: 'googlecpp'
          output-file-path: pr/report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          gh-repository: 'github.com/Malmahrouqi3/malmahrouqi3.github.io'
          gh-pages-branch: 'main'
          benchmark-data-dir-path: 'docs/documentation/bench'
          ref: ${{ github.event.inputs.tag || github.ref_name }}